#!/bin/zsh
# set -x

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"

CONFIG_DIR="${XDG_DATA_HOME:-${HOME}/.config}"

# # (.) at end tells zsh to only return files
# for file in $DOTFILES_DIR/.*(.); do
#     echo ln -s $file `basename $file`
# done
#
# for dir in $DOTFILES_DIR/*(/); do
#     echo $dir
# done
#

cd ~

DOTFILES=(zim/.zshrc zim/.zimrc .wezterm.lua .ripgreprc)

for file in $DOTFILES; do
    link_name=$(basename "$file")
    ln -snf $DOTFILES_DIR/$file $link_name
done

# Tmux special case
ln -snf $DOTFILES_DIR/tmux/tmux.conf .tmux.conf

DOTFILE_DIRS=(nvim stylua eza)

for dir in $DOTFILE_DIRS; do
    ln -snf $DOTFILES_DIR/$dir $CONFIG_DIR/$dir
done
