line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
column_width = 160
quote_style = "AutoPreferSingle"
# call_parentheses = "None"
collapse_simple_statement = 'Always'
[sort_requires]
  enabled = true
