name: Build Minimal Init

on:
  push:
    paths:
      - "nvim/lua/options.lua"
      - "nvim/lua/keymaps.lua"
      - "nvim/scripts/gen-minimal-init.sh"
  workflow_dispatch:

jobs:
  build-minimal-init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x scripts/gen-minimal-init.sh
        working-directory: ./nvim

      - name: List scripts directory for debugging
        run: ls -l scripts
        working-directory: ./nvim

      - name: Run gen-minimal-init.sh script
        run: scripts/gen-minimal-init.sh
        working-directory: ./nvim

      - name: Check for changes to minimal-init.sh
        id: git_diff
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if git status --porcelain minimal-init.sh | grep '^ M'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
        working-directory: ./nvim

      - name: Commit and push minimal-init.sh if changed
        if: steps.git_diff.outputs.changed == 'true'
        run: |
          git add minimal-init.sh
          git commit -m "chore: update minimal-init.sh [auto]"
          git push
        working-directory: ./nvim
